### ISSUE TITLE
Instructions For Updating Database Lacking

### ISSUE THREAD

**Issue by DarioS** [Kingsford-Group/kourami#1]
The database provided for downloading is over 1 year old and hundreds of new alleles are available in version 3.28.0. There is no script provided to produce a database folder of files as required by the software, so it'll be hard for end-users to use any version other than 3.24.0 of IMGT-HLA.

**Comment by heewookl** [comment]
I am working on the documentation and the update is coming shortly. Thank you.

**Comment by heewookl** [comment]
This was done in July. See https://github.com/Kingsford-Group/kourami/blob/master/preprocessing.md#2-creating-kourami-hla-panel-and-merged-msas-from-another-version-release-of-imgthla-db-or-a-custom-version
