### ISSUE TITLE
formatIMGT

### ISSUE THREAD

**Issue by ikmb** [Kingsford-Group/kourami#10]
Should this line in formatIMGT.sh 
java -Xmx$jvm_memory -cp $SCRIPTD/../target/Kourami.jar FormatIMGT $input_msa $imgt_ver_num $db_base 2> $logfil

not rather read

java -Xmx$jvm_memory -cp $kourami FormatIMGT $input_msa $imgt_ver_num $db_base 2> $logfil

**Comment by heewookl** [comment]
Thanks for pointing out. As long as you are using Maven to compile, the current line should work fine. Since there is a code block that checks for the location of Kourami jar and already defined as $kourami, what you suggested is the better way to go.
