### ISSUE TITLE
The last three columns in new output 

### ISSUE THREAD

**Issue by wangdatou2009** [Kingsford-Group/kourami#13]
Hi, after update to current releases, I notice there are 8 columns in the output result, can you explain what the last three columns mean. Thanks

**Comment by heewookl** [comment]
Hi,

First, I want to mention that Kourami outputs 2 solutions alleles by simultaneously finding the best pair of paths through HLA-graph in terms on weights and amount of phasing information.

Three additional columns are basically weights of bottleneck edges(edges with minimal weight)

6th column: reports the combined bottleneck weights of both paths at a position. This is not necessarily same as the sum of column 7 and 8. 
7th column: Weight of the bottleneck edge in path 1
8th column: Weight of the bottleneck edge in path 2

I will also update the readme page as well.
