### ISSUE TITLE
Error: Could not find or load main class FormatIMGT

### ISSUE THREAD

**Issue by zezzipa** [Kingsford-Group/kourami#18]
Hi,

This might be a stupid question but I don't know how to solve it. I have been trying to make my own reference but when I run the formatIMGT.sh I get the following error message:
An error has occurred while formating IMGT/HLA DB.

and when looking in the log file it says: 
Error: Could not find or load main class FormatIMGT

These errors don't give much clue to how to fix this issue so what can I do to get the formatIMGT to work?

Thankful for help.
Kind regards,
Jessika

**Comment by heewookl** [comment]
Hi, thanks for taking an interest in using Kourami.

It sounds like you may not have successfully compiled and built a Kourami jar file. Did you follow the installation instruction on 
```https://github.com/Kingsford-Group/kourami/blob/master/README.md``` and either used maven or ant to build? 

```formatIMGT.sh``` script calls Kourami jar either located under build or target directory but you are probably missing the jar. If you have downloaded the source, please follow the README to build Kourami and rerun ```formatIMGT.sh```

Thanks!

**Comment by heewookl** [comment]
Glad it's working!
