### ISSUE TITLE
Exception in thread "main" java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by raivokolde** [Kingsford-Group/kourami#2]
I was trying to run the tool (on a 30x whole genome sequence) and it ran fine for a while, but then ended up with this error (on READ LOADING step). The server that I run it on should have 256Gb memory, I was hoping that this would be enough. Is it possible that the Memory problem is on Java side and I can just increase it somehow or do I need a bigger computer?

**Comment by heewookl** [comment]
As mentioned in our manuscript, Kourami only requires roughly 4GB of RAM to analyze 30X coverage data. 

I believe JVM sets its default heap size based on currently available memory and it can be different from machine to machine. You can find your default initial and max heapsize by issuing the following command line:
```
java -XX:+PrintFlagsFinal -version | grep HeapSize 
```

However, in your case I doubt this is the problem.

What bam file are you using? The Kourami takes a bam containing HLA loci reads mapped to reference panel that is created for Kourami based on IMGT/HLA database.  My guess is that you may have just fed in the bam aligned to GRCh38? 

I will update the code to check the bam prior to running and also I am writing a better documentation along with preprocessing scripts(extracting reads from GRCh38 bam then to Kourami panel). Expect to see these updates in the next couple of days. Thank you!

**Comment by raivokolde** [comment]
Thanks for quick response! I indeed fed it a full bam file. It would be great to see some preprocessing steps. Although not directly part of the method, it would make usage of the tool so much easier. The bam files are so big that it is a pain to test different approaches for preprocessing even if they are fairly straightforward.

**Comment by DarioS** [comment]
> The Kourami takes a bam containing HLA loci reads mapped to reference panel that is created for Kourami based on IMGT/HLA database. My guess is that you may have just fed in the bam aligned to GRCh38?

This advice contradicts the draft article. On page 6 of the PDF, it states that:

> Kourami takes alignment of WGS to the human genome as an input in the BAM format ... we extract paired-end reads aligned to all known HLA loci in chromosome 6 ...

Kourami doesn't have any options for specifying the start and end coordinates of the genes, so is it hard-coded to GRCh38? What if a user wants to use data mapped to hg19 in which the HLA genes have different positions?

**Comment by heewookl** [comment]
@raivokolde 

Preprocessing scripts have been uploaded and the document explaining how to use the preprocessing scripts to generate input bam for Kourami can be found [here](https://github.com/Kingsford-Group/kourami/blob/master/preprocessing.md)

Please make sure `git clone` or `git pull` to redownload the latest release [here](https://github.com/Kingsford-Group/kourami/releases/tag/v0.9.2)

Thanks!
