### ISSUE TITLE
Typing of non-key exons for major HLA genes

### ISSUE THREAD

**Issue by npilshchikova** [Kingsford-Group/kourami#22]
Is it possible to receive complete exon sequences and also to get from Kourami actual 6-digit result without any G-grouping? As I can understand from corresponding article, Kourami uses all exon sequences available in IMGT-HLA, why only key exons are included in output?

**Comment by heewookl** [comment]
Currently, this is not supported. This may be possible in the future by incorporating long reads.

**Comment by davetang** [comment]
May I inquire whether there has been any update on assembling "non-core" exons, i.e. not just exon 2 and 3 for class I and exon 2 for class II? I'm trying to use Kourami to type a sample but the distinguishing nucleotide between two alleles is outside the core exon. Thank you.
