### ISSUE TITLE
Need details for pre-processing

### ISSUE THREAD

**Issue by MattBrauer** [Kingsford-Group/kourami#3]
An error indicates:
```
The input BAM MUST be aligned to the set of IMGT/HLA alleles in /gne/home/matthejb/tools/kourami/db
Please use the recommended preprocessing steps explained on the github page:
https://github.com/Kingsford-Group/kourami
```
but there does not seem to be such an explanation. I believe I have figured this out, but explicit instructions would be welcome.

**Comment by heewookl** [comment]
It will be posted shortly. Thank you.

**Comment by heewookl** [comment]
Preprocessing [document](https://github.com/Kingsford-Group/kourami/blob/master/preprocessing.md) as well as [new release](https://github.com/Kingsford-Group/kourami/releases/tag/v0.9.2) has been posted. Thank you.
