### ISSUE TITLE
Kourami stalls upon Bubble Processing and Path Assembly for DPB1

### ISSUE THREAD

**Issue by danilovkiri** [Kingsford-Group/kourami#31]
Hi!

I've encountered a problem using  Kourami v0.9.6 with IMGTHLA v3.42.0 (preprocessed as per instructions): a single human 30x WGS 100 bp read-length BAM file causes stalling of Kourami at Bubble Processing and Path Assembly for DPB1. Kourami manages to successfully process all previous loci (A, B, C, DQ, DR, etc.). While stalling, Kourami still uses computational resources and its processes are active. It has been stalled for 12 hours already and still does not proceed to the next step.
The observed issue does not happen with any other similar BMA files, which are successfully processed extremely fast within 5 min.
I can provide the `on_KouramiPanel.bam` file if necessary.

@ckingsford Could you please tell me whether Kourami is still supported? It seems like all of the latest issues do not have any impact. Thank you.

**Comment by heewookl** [comment]
Hi, 

Would you be able to share the bam file? Thank you. It could be due to the updated alleles in IMGTHLA.

**Comment by danilovkiri** [comment]
Hi @heewookl 
Unfortunately, I'm unable to reproduce this error now. I'm closing the issue for now.
