### ISSUE TITLE
IndexOutOfBoundsException in HLA.main

### ISSUE THREAD

**Issue by MattBrauer** [Kingsford-Group/kourami#4]
```
java -jar ~/tools/kourami/target/Kourami.jar -o test -d ~/tools/kourami/db sample2.bam
```
(where sample2 comprises reads mapped to the reference in db) results in the error:
```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:653)
        at java.util.ArrayList.get(ArrayList.java:429)
        at HLAGraph.processBubbles(HLAGraph.java:929)
        at HLAGraph.countBubblesAndMerge(HLAGraph.java:869)
        at HLA.countBubblesAndMerge(HLA.java:372)
        at HLA.main(HLA.java:564)
```
The output contains a stretch of lines reading 'This should NOT HAPPEN', which makes me think that something just might possibly not be happening correctly.

Note that the BAM file was built by filtering chr6 and unmapped reads from a GRCh38 alignment, then realigning resulting fastq files to the db reference.

Output:
[test.txt](https://github.com/Kingsford-Group/kourami/files/1019534/test.txt)

BAM file statistics:
flagstats:
[flagstat.txt](https://github.com/Kingsford-Group/kourami/files/1019613/flagstat.txt)

stats:
[stats.txt](https://github.com/Kingsford-Group/kourami/files/1019619/stats.txt)

**Comment by heewookl** [comment]
Thanks for letting us know of the error.
What is the sequencing coverage of WGS? And can you upload a file just consisting of @SQ tags from bam headers (from the original GRCh38 bam you have).

-hl

**Comment by MattBrauer** [comment]
Coverage is >30x.
```
samtools idxstats > orig.idxstats.txt
samtools view -H original.bam >orig.header.txt
```
files attached.
[orig.header.txt](https://github.com/Kingsford-Group/kourami/files/1019718/orig.header.txt)
[orig.idxstats.txt](https://github.com/Kingsford-Group/kourami/files/1019719/orig.idxstats.txt)

**Comment by heewookl** [comment]
Please look at the [document posted](https://github.com/Kingsford-Group/kourami/blob/master/preprocessing.md).

Looks like your reference genome consists of primary assembly and ALT sequences only. Please use `alignAndExtract_hs38Alt.sh` under `scripts` directory to generate the input bam for Kourami. Thank you.
