### ISSUE TITLE
Hard-coded HLA Genes in Java Code

### ISSUE THREAD

**Issue by DarioS** [Kingsford-Group/kourami#5]
The software is hard-coded to only work on a few of the HLA genes, but there are many others with numerous alleles in IMGT/HLA (e.g. HLA-E, HLA-G, etc.). The partially-ordered graph method seems generic enough that it should work with any input genes - HLA isn't the only polymorphic gene family in the genome. Also, the software seems bloated because it copies and pastes code statements instead of using loops. For example,

```
    public void printWeights(){
	this.hlaName2Graph.get("A").traverseAndWeights();
	this.hlaName2Graph.get("B").traverseAndWeights();
	this.hlaName2Graph.get("C").traverseAndWeights();
	this.hlaName2Graph.get("DQA1").traverseAndWeights();
	this.hlaName2Graph.get("DQB1").traverseAndWeights();
	this.hlaName2Graph.get("DRB1").traverseAndWeights();
}
```
seems wasteful because the alleles are defined elsewhere `String[] list = {"A" , "B" , "C" , "DQA1" , "DQB1" , "DRB1"};` and could simply be looped over.

**Comment by heewookl** [comment]
Updated and will be incorporated in the next release.
