### ISSUE TITLE
Software Doesn't Validate Input Parameters

### ISSUE THREAD

**Issue by DarioS** [Kingsford-Group/kourami#6]
If the BAM file name is mistyped, Kourami doesn't check if the file exists and commences reference graph construction. Good software design means the input parameters are validated before any processing is done, so that the error occurs early.

```
$ java -jar Kourami.jar -d databases/kourami/ -o test /path/to/nonExistent.bam
----------------REF GRAPH CONSTRUCTION--------------
---------------- READ LOADING --------------
htsjdk.samtools.util.RuntimeIOException: java.io.FileNotFoundException: /path/to/nonExistent.bam (No such file or directory)
```

Also, the reference graph construction happens every time I run the command. Why is it repeated when it could be done once and saved to disk? I'm glad software such as `bowtie` only builds its index once (e.g. using `bowtie-build`) and allows it to be reused in future analyses.

**Comment by heewookl** [comment]
some levels of input parameter validation has been incorporated in the latest release. 

We looked into serializing the graph construction but it turns out that there isn't much of gain in speed and performance.
