### ISSUE TITLE
Numerous Software Dependencies of Scripts

### ISSUE THREAD

**Issue by DarioS** [Kingsford-Group/kourami#7]
The preprocessing scripts have a number of software dependencies, some of which seem unnecessary. For example, `bamUtil` is required by the script, but the same task can done by `samtools`.

```
samtools fastq -1 aSample_R1.fastq -2 aSample_R2.fastq aSample.bam
```

Also, some of the progress messages are also wrong. For example, in the script `alignAndExtract_hs38.sh`, on line 69:

```
echo ">>>>>>>>>>>>>>>> extracting reads mapping to HLA loci and ALT contigs (38)"
```

The script is for when the reads were **not** mapped to HLA and ALT contigs.

It'd be convenient if it was available as a Docker container to make it easier to use.

**Comment by heewookl** [comment]
We find bamUtil's fastq extraction more convenient for our purpose.

The progress message you are referring to is actually correct, it uses `-F 0x4`filtering to exclude unmapped reads and include only the mapped.
