### ISSUE TITLE
Error: Could not find or load main class HLA

### ISSUE THREAD

**Issue by wangdatou2009** [Kingsford-Group/kourami#8]
Follow the instruction step by step, and mnv install was done successfully.

Why the error message still show up after I type

java -jar target/Kourami.jar

**Comment by heewookl** [comment]
Thanks for trying out Kourami. 

It's strange that mvn install was successful and you are getting the error. 

In order for me to resolve the error for you, could you please provide little more detail? (listed below. please provide the output from each command): 

1. mvn version and the version of jdk your mvn is using by running:
```
mvn -version
```

2. java version you are using:
```
java -version
```

3. content of the mamnifest file in your jar:
```
unzip -p target/Kourami.jar META-INF/MANIFEST.MF
```

4. List of dependency jars:
```
ls -l target/dependency-jars/ 
```

Finally, could you also try the precompiled version by downloading from the latest release ( https://github.com/Kingsford-Group/kourami/releases/download/v0.9.4/kourami_v0.9.4_bin.tar )?

**Comment by wangdatou2009** [comment]
Thanks for your reply! I successfully run that with your pre-compiled version. But I still did not get the reason why I failed to install that from source code. Following is the information

1.mvn -version
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_131, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-75-generic", arch: "amd64", family: "unix"

2.java -version
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2ubuntu1.16.04.3-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

3.unzip -p target/Kourami.jar META-INF/MANIFEST.MF
Built-By: wangdatou2009
Class-Path: dependency-jars/jgrapht-core-0.9.1.jar dependency-jars/hts
 jdk-2.1.1.jar dependency-jars/ngs-java-1.2.2.jar dependency-jars/comm
 ons-jexl-2.1.1.jar dependency-jars/commons-logging-1.1.1.jar dependen
 cy-jars/snappy-java-1.0.3-rc3.jar dependency-jars/commons-compress-1.
 4.1.jar dependency-jars/xz-1.5.jar dependency-jars/ant-1.8.2.jar depe
 ndency-jars/ant-launcher-1.8.2.jar dependency-jars/commons-cli-1.4.ja
 r dependency-jars/fastutil-7.0.13.jar dependency-jars/jgrapht-ext-0.9
 .1.jar dependency-jars/jgraphx-2.0.0.1.jar dependency-jars/jgraph-5.1
 3.0.0.jar dependency-jars/jgrapht-demo-0.9.1.jar
Created-By: Apache Maven 3.3.9
Build-Jdk: 1.8.0_131
Main-Class: HLA

4.ls -l target/dependency-jars/
 1933743 Oct 17 17:31 ant-1.8.2.jar
12322 Oct 17 17:31 ant-launcher-1.8.2.jar
 53820 Oct 17 17:31 commons-cli-1.4.jar
241367 Oct 17 17:31 commons-compress-1.4.1.jar
267634 Oct 17 17:31 commons-jexl-2.1.1.jar
60686 Oct 17 17:31 commons-logging-1.1.1.jar
17875641 Oct 17 17:31 fastutil-7.0.13.jar
 1357827 Oct 17 17:31 htsjdk-2.1.1.jar
296115 Oct 17 17:31 jgraph-5.13.0.0.jar
 351208 Oct 17 17:31 jgrapht-core-0.9.1.jar
 12131 Oct 17 17:31 jgrapht-demo-0.9.1.jar
34223 Oct 17 17:31 jgrapht-ext-0.9.1.jar
819906 Oct 17 17:31 jgraphx-2.0.0.1.jar
 60129 Oct 17 17:31 ngs-java-1.2.2.jar
990264 Oct 17 17:31 snappy-java-1.0.3-rc3.jar
 99555 Oct 17 17:31 xz-1.5.jar

Again, thanks a lot for you hard work!

**Comment by heewookl** [comment]
Glad that the precompiled jar worked for you. I am also not sure why maven-compiled jar isn't working for you. I suspect it's probably due to how CLASSPATH is set.

Could you try running 2 commands below and see if either of these works? Thank you.
1.
```
java -cp target/Kourami.jar HLA
```

2.
```
java -cp . -jar target/Kourami.jar
```

**Comment by wangdatou2009** [comment]
1.java -cp target/Kourami.jar HLA
Error: Could not find or load main class HLA
2.java -cp . -jar target/Kourami.jar
Error: Could not find or load main class HLA
3. jar -tfv target/Kourami.jar
Error: Could not find or load main class HLA

**Comment by heewookl** [comment]
Ok. That's really strange. For the third one (``` jar -tfv target/Kourami.jar```) you should just get contents of the jar file and that error message shouldn't be there. 

Can you retry the command? OR since unzip worked previously for you to get the content of the manifest file, perhaps the following command might be better:
```
unzip -l target/Kourami.jar
```

Thank you.

**Comment by wangdatou2009** [comment]
Archive:  target/Kourami.jar
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  2017-10-17 17:31   META-INF/
      776  2017-10-17 17:31   META-INF/MANIFEST.MF
     1559  2017-10-17 17:31   LICENSE
     4818  2017-10-17 17:31   README.md
        0  2017-10-17 17:31   META-INF/maven/
        0  2017-10-17 17:31   META-INF/maven/kingsford-group/
        0  2017-10-17 17:31   META-INF/maven/kingsford-group/Kourami/
     3041  2017-10-07 02:33   META-INF/maven/kingsford-group/Kourami/pom.xml
      107  2017-10-17 17:31   META-INF/maven/kingsford-group/Kourami/pom.properties
---------                     -------
    10301                     9 files

**Comment by heewookl** [comment]
I think you must've downloaded the precompiled tarball and ran ```mvn install``` there. This will create a jar with just the manifest file, readme, license and maven related files. You jar file does not contain any of the class files.

You should either get the latest release of the source ( https://github.com/Kingsford-Group/kourami/archive/v0.9.4.tar.gz ) or you can simply run ```git clone git@github.com:Kingsford-Group/kourami.git```

Then you can move into the "kourami" directory and run ```mvn install```

I am pretty sure this will work but please let me know if it works for you. Thank you.

**Comment by wangdatou2009** [comment]
thanks! I re-downloaded all files, and everything is fine now. Please look at the another question if you have time, it is already midnight EST, right?
