### ISSUE TITLE
How to type HLA beyond A.B.C.DQA1.DQB1 and DRB1

### ISSUE THREAD

**Issue by wangdatou2009** [Kingsford-Group/kourami#9]
such like DPA1 DPB1
DRA
DRB3
DRB4
DRB5
and DM or DO?
Even the quality is not that good for above gene, I really wanna see the possible call set.

Thanks

**Comment by wangdatou2009** [comment]
I found -a option, but it still did not output DPB1, which is very important for HLA analsis

**Comment by heewookl** [comment]
```-a``` option was added for typing of additional loci other than the 6 mainly popular loci.  I didn't realize that the README page wasn't updated to show the new option. I will update the README page.

DPB1 should normally be outputted unless you don't have enough coverage across the locus. Are you running Kourami with paired-end WGS with high-coverage (at least 30x, preferably 40x+) ?

Thanks.

**Comment by wangdatou2009** [comment]
[test.zip](https://github.com/Kingsford-Group/kourami/files/1393478/test.zip)
Thanks a lot! 
I am using paired-end WGS data with 80X from Illumina Novaseq S4 chip.  Can you check the bam file I uploaded?  I zipped it.
I used pre-processing script alignAndExtract_hs38DH.sh and default HLA db. 
Originally the fastq file was aligned to GATK hg38 reference bundle, so it is same as the reference in LiHeng or yours a+b+c+d reference.

**Comment by heewookl** [comment]
I've ran your test file and you are correct that Kourai does not output DPB1 results. I looked at the log and DPB1 coverage across the typing region seems to be too low to assemble through the graph. I will look at in more in detail and keep you updated. Thank you.

**Comment by wangdatou2009** [comment]
I‘ve also run XHLA by craig venter‘group on the same file. It can output DPB1. I think your method not rely too much on coverage, if the low but high quality coverage exist, graph still can connected, right?

**Comment by wangdatou2009** [comment]
And also I have a HLA reference for this sample, which is done by Amplicon seq. The result of G H J, DRA1,DMA,DMB and DOA did not match Kourami's call set. 
And for G, it can not tell the right 8 digits resolution(Kourami call 7 possible alleles), why just stop at 6 digits?

**Comment by heewookl** [comment]
Kourami focuses on the peptide binding regions of HLA alleles, thus output sequences at 6-digit resolution. 

Kourami is an assembly method which constructs sequences. These additional loci do not have lots of alleles that are reported in the current database, and because of this, typing results may not be reliable. You should checked the assembled sequence and compare directly at the sequence level. 

For DRA DMA DMB and ODA, assembled sequences are perfect match to one of the databse alleles (what's reported in the result file), are you saying you have amplicon confirmation of these sequences?

Also, IMGT database doesn't provide 'G' grouping information for DOA, DMA, DMB, DRA, G, H, and J and there may be more alleles that are identical to the ones that are output by Kourami when an assembled sequence is a perfect match to an entry in the db. Updates will be released to report all identical alleles.

**Comment by wangdatou2009** [comment]
Thanks a lot! HLA DPB1 is a really important as β-chain for HLA-DP, so is that possible it can do some prediction on this gene? 

For DRA DMA DMB DOA or GHJ, they are not that important for HLA research. Maybe you could lower the priority.

**Comment by heewookl** [comment]
DPB1 is already supported, however, there may be some problems with current extraction methods. 

Could you try the updated [extraction-script](https://raw.githubusercontent.com/Kingsford-Group/kourami/readExtractionALT/scripts/alignAndExtract_hs38DH.sh) from readExtractionALT branch? Thanks. You will need to re-extract reads using the updated script from your original GRCh38+Decoy+ALT+HLA bam.  Would it be possible for you to upload the bam with extracted reads for me to test as well? Thank you.

**Comment by wangdatou2009** [comment]
sure. Let me do it now

**Comment by wangdatou2009** [comment]
Bug
$ ./scripts/alignAndExtract_hs38DH.sh

./scripts/alignAndExtract_hs38DH.sh: line 7: syntax error near unexpected token `newline'
./scripts/alignAndExtract_hs38DH.sh: line 7: `<!DOCTYPE html>'

**Comment by wangdatou2009** [comment]
[test.zip](https://github.com/Kingsford-Group/kourami/files/1411220/test.zip)

**Comment by heewookl** [comment]
Thank you! This should work fine. I got 
DPB1*02:01:02G  264     1.0     264     264
DPB1*21:01      264     1.0     264     264

**Comment by heewookl** [comment]
@wangdatou2009  Have you had a chance to run it yourself? Thanks.

**Comment by tinyheero** [comment]
Sorry to bring this thread back, but is the DPA1 locus also typed?
